Http call example
buntec/ff4s pull request #129
Opened 2023-05-15 21:18 UTC by ramytanios

2023-05-17 19:22 UTC, buntec requested changes
I'll stop here for now. Haven't looked at the subscriptions example yet.

2023-05-17 19:22 UTC, buntec commented on docs/examples/data-fetch.md
> +on each button click using the [numbers API](http://numbersapi.com/#42).
```suggestion
# Data Fetching

Fetching data from the back-end is probably the most common type of IO in single-page applications.
In this example we illustrate this pattern in `ff4s` using a simple HTTP GET 
request to the [numbers API](http://numbersapi.com/), which returns a random fact
about any number that we supply.
```

2023-05-17 19:22 UTC, buntec commented on docs/examples/data-fetch.md
> +The random fact is also naturally modelled by a case class with a `circe` codec:
```suggestion
We model the JSON API response using a case class with a derived [circe](https://circe.github.io/circe/) decoder:
```

2023-05-17 19:22 UTC, buntec commented on docs/examples/data-fetch.md
> +  implicit val codec: Codec[Fact] = deriveCodec
```suggestion
  implicit val decoder: Decoder[Fact] = deriveDecoder
```

2023-05-17 19:22 UTC, buntec commented on docs/examples/data-fetch.md
> +```
```suggestion
The action encoding is straightforward.

```scala mdoc:js:shared
sealed trait Action
case object GetRandomFact extends Action
case class SetFact(fact: Option[Fact]) extends Action
case class SetNumber(number: Int) extends Action
```
```

2023-05-17 19:22 UTC, buntec commented on docs/examples/data-fetch.md
> +}
```suggestion
object Store {

  def apply[F[_]: Async]: Resource[F, ff4s.Store[F, State, Action]] =
    ff4s.Store[F, State, Action](State()) { store =>
      _ match {
        case SetFact(fact)     => _.copy(fact = fact) -> none
        case SetNumber(number) => _.copy(number = number) -> none
        case GetRandomFact =>
          state =>
            (
              state,
              ff4s
                .HttpClient[F]
                .get[Fact](s"http://numbersapi.com/${state.number}?json")
                .flatMap(fact => store.dispatch(SetFact(fact.some)))
                .some
            )

      }
    }

}
```

2023-05-17 19:22 UTC, buntec commented on docs/examples/data-fetch.md
> +
```suggestion
The only interesting bit in the store is the handling of `GetRandomFact`. Note how we retrieve the number from the state and how we are updating the state with the retrieved fact using `store.dispatch`. A more realistic example would include error handling of failed requests.
```

2023-05-17 19:22 UTC, buntec commented on docs/examples/data-fetch.md
> +with a random fact through the `dispatch` method of the store that returns an `F[Unit]`. Note that the effect is optional hence the presence of the `.some`.
```suggestion
```

2023-05-17 19:22 UTC, buntec commented on docs/examples/data-fetch.md
> +```
```suggestion
The construction of `ff4s.App` and `ff4s.IOEntryPoint` is straightforward and omitted for brevity.
```

2023-05-17 19:38 UTC, ramytanios commented
> I'll stop here for now. Haven't looked at the subscriptions example yet.



> I'll stop here for now. Haven't looked at the subscriptions example yet.

Ok thanks - let me then update the text based on the suggestions

2023-05-17 19:39 UTC, ramytanios commented
@buntec  ok thanks -- let me then update the text of the cancellation based on the suggestions

2023-05-18 05:53 UTC, buntec requested changes

2023-05-18 05:53 UTC, buntec commented on docs/examples/cancellation.md
> +                SetNumber(el.value.toIntOption.getOrElse(0)).some
```suggestion
                // A more realistic example would include input validation. Here we simply fall back to `0`.
                SetNumber(el.value.toIntOption.getOrElse(0)).some
```

2023-05-18 05:53 UTC, buntec commented on docs/examples/subscription.md
> +# Subscription
```suggestion
# Subscriptions
```

2023-05-18 05:53 UTC, buntec commented on docs/examples/subscription.md
> +      }
```suggestion
      .flatTap {
        // subscribe to changes in user input and trigger debounced API calls
        _.state
          .map(_.number)
          .discrete
          .changes
          .debounce(1.second)
          .evalMap(_ => store.dispatch(GetRandomFact))
          .compile
          .drain
          .background
      }
```

2023-05-18 05:53 UTC, buntec commented on docs/examples/subscription.md
> +[numbers API](http://numbersapi.com/), where each request is sent based on user input.
```suggestion
The fact that the store in ff4s is a `Resource` and that `store.state` is a `Signal` allows us to subscribe to updates of (part of) the state and react to them. A common use case is debouncing API calls based on user input. 
```

2023-05-18 05:53 UTC, buntec commented on docs/examples/subscription.md
> +with high frequency while we do not want to react to each single change.
```suggestion

```

2023-05-18 07:54 UTC, buntec commented
Thanks so much!

2023-05-18 07:54 UTC, merged